galacticcouncil/warehouse

- Cargo.toml
- faucet/Cargo.toml
- faucet/README.md
- faucet/src/lib.rs
- faucet/src/mock.rs
- faucet/src/tests.rs
Simple faucet pallet - just copied here as it was implemented originally in HydraDX-node.
> feat: add simple faucet pallet

- price-oracle/Cargo.toml
- price-oracle/src/lib.rs
- price-oracle/src/mock.rs
remove basilisk dependencies
Fixes: #14
> build: remove dependencies

- traits/Cargo.toml
- traits/src/lib.rs
Required by https://github.com/galacticcouncil/Basilisk-node/issues/262
> feat: get fee from amm trait

- price-oracle/Cargo.toml
- price-oracle/src/benchmarking.rs
- price-oracle/src/lib.rs
- price-oracle/src/tests.rs
- traits/Cargo.toml
- traits/src/lib.rs
> refactor: remove panic from on_finalize

- faucet/Cargo.toml
- price-oracle/Cargo.toml
- relaychain-info/Cargo.toml
- traits/Cargo.toml
- transaction-multi-payment/Cargo.toml
related to https://github.com/galacticcouncil/Basilisk-node/issues/321
> chore: upgrade to polkadot v0.9.15

- transaction-multi-payment/Cargo.toml
- transaction-multi-payment/src/lib.rs
- transaction-multi-payment/src/mock.rs
> refactor: adjust fee calculation to new spot price

- .github/workflows/format.yml
- asset-registry/src/benchmarking.rs
- asset-registry/src/lib.rs
- asset-registry/src/mock.rs
- asset-registry/src/tests.rs
- asset-registry/src/types.rs
- asset-registry/src/weights.rs
- faucet/src/mock.rs
- transaction-multi-payment/src/lib.rs
- transaction-multi-payment/src/mock.rs
> ci: Add check for code format

- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/mock.rs
- nft/src/tests.rs
> feat: NFT implements non-fungible traits

- asset-registry/Cargo.toml
- asset-registry/src/lib.rs
- faucet/Cargo.toml
- faucet/src/lib.rs
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/mock.rs
- nft/src/tests.rs
- price-oracle/Cargo.toml
- price-oracle/src/lib.rs
- price-oracle/src/tests.rs
- relaychain-info/Cargo.toml
- relaychain-info/src/lib.rs
- transaction-multi-payment/Cargo.toml
- transaction-multi-payment/src/lib.rs
related to [326](https://github.com/galacticcouncil/Basilisk-node/issues/326)
> refactor: events to structs

- transaction-multi-payment/src/lib.rs
- transaction-multi-payment/src/tests.rs
...to not set fee currency if there is native balance in the account.
> Change Account Callback

- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/mock.rs
- nft/src/tests.rs
- traits/Cargo.toml
- traits/src/lib.rs
- traits/src/nft.rs
* `CtrateTypedClass` trait to allow create typed classes from our pallets.
* `ReserveClassIdUpTo` trait for checking if id is from nft's reserved range. This is usable to check our pallets configuration e.g if we configured pallet's nft class from reserved range.
> feat:  CreateTypedClass and ReserveCassIdUpTo traits

- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
Add metadat to some nft events. 
Fixed #73
> fix: add metadata to nft events

- transaction-multi-payment/Cargo.toml
- transaction-multi-payment/src/mock.rs
- transaction-multi-payment/src/tests.rs
> test(XYK): Add tests for hooks

- Cargo.lock
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
> feat(nft): test ownership in nft pallet

- nft/Cargo.toml
- nft/src/lib.rs
> refactor(nft): call get_destroy_witness from trait implementation

- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/mock.rs
> feat(nft): remove ProtocolOrigin

- Cargo.lock
- nft/src/lib.rs
> docs(nft): add missing docs

- Cargo.lock
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
> feat(nft): enable maybe_check_owner in nft destroy trait

- Cargo.lock
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
> feat(nft): test reserved id in `create_collection`

- Cargo.lock
- nft/Cargo.toml
- nft/src/weights.rs
> feat(nft): default weights

- Cargo.lock
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
> refactor(nft): returning of `DestroyWitness`

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
- liquidity-mining/src/tests/claim_rewards.rs
- liquidity-mining/src/tests/create_yield_farm.rs
- liquidity-mining/src/tests/destroy_yield_farm.rs
- liquidity-mining/src/tests/mod.rs
- liquidity-mining/src/tests/redeposit_lp_shares.rs
- liquidity-mining/src/tests/resume_yield_farm.rs
- liquidity-mining/src/tests/terminate_global_farm.rs
- liquidity-mining/src/tests/terminate_yield_farm.rs
- liquidity-mining/src/tests/tests.rs
- liquidity-mining/src/tests/update_yield_farm.rs
- liquidity-mining/src/tests/withdraw_lp_shares.rs
- liquidity-mining/src/types.rs
- traits/Cargo.toml
- traits/src/liquidity_mining.rs
This PR fixes #115 and refactoring `Deleted` state of farm to `Terminated`
> fix: LM global farm's paid accumulated rewards

- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
- traits/Cargo.toml
- traits/src/nft.rs
Fixes https://github.com/galacticcouncil/warehouse/issues/97
> refactor(NFT): remove unused `Create` trait implementation

- Cargo.lock
- nft/Cargo.toml
- nft/src/lib.rs
- nft/src/tests.rs
- traits/Cargo.toml
- traits/src/nft.rs
Related to https://github.com/galacticcouncil/warehouse/issues/97#issuecomment-1311054180
> feat: add metadata param to `create_typed_collection`

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
- liquidity-mining/src/tests/claim_rewards.rs
- liquidity-mining/src/tests/mock.rs
- liquidity-mining/src/tests/withdraw_lp_shares.rs
- traits/Cargo.toml
- traits/src/liquidity_mining.rs
> feat: claim rewards in the withdraw_lp_shares()

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
Moved `reward` calculation in `sync_global_farm` to math repo so it can be used by frontend.
> feat: lm use latest math

- Cargo.lock
- currencies/Cargo.toml
- currencies/src/lib.rs
- currencies/src/mock.rs
- currencies/src/tests.rs
> feat: implement `NamedMultiReservableCurrency` for `pallet_currencies`

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
- traits/Cargo.toml
- traits/src/liquidity_mining.rs
This PR changes type of `get_token_value_of_lp_shares` param in liquidity-mining's trait to support closure as its value.
> feat: omnipool liquidity mining changes

- Cargo.lock
- duster/Cargo.toml
- duster/src/lib.rs
- duster/src/migration.rs
This PR adds migration for pallet duster to v1
> feat: duster migration

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
- liquidity-mining/src/tests/create_yield_farm.rs
- liquidity-mining/src/tests/resume_yield_farm.rs
- liquidity-mining/src/tests/tests.rs
- liquidity-mining/src/tests/update_yield_farm.rs
- liquidity-mining/src/types.rs
This PR fixes: 
* #176 
* #177
* #181
> fix: liquidity mining issues from audit

- Cargo.lock
- liquidity-mining/Cargo.toml
- liquidity-mining/src/lib.rs
- liquidity-mining/src/tests/create_yield_farm.rs
- liquidity-mining/src/tests/deposit_lp_shares.rs
- liquidity-mining/src/tests/redeposit_lp_shares.rs
- liquidity-mining/src/tests/tests.rs
> fix: liquidity mining valued shares >= min_deposit

- Cargo.lock
- ema-oracle/Cargo.toml
- liquidity-mining/Cargo.toml
- stableswap/Cargo.toml
This is required for omnipool withdrawal fee implementation.
> feat: omnipool withdrawal fee math

- Cargo.lock
- currencies/Cargo.toml
- currencies/src/fungibles.rs
- currencies/src/lib.rs
- currencies/src/mock.rs
- currencies/src/tests.rs
- currencies/src/tests_fungibles.rs
Adds implementations of fungible traits for currencies adapter.
> feat: fungible trait implementation for currencies 
