galacticcouncil/warehouse

traits/Cargo.toml, traits/src/lib.rs
Liquidity mining pallet need to know share token from amm `AssetPair`.
=> feat: get share token from amm

traits/Cargo.toml, traits/src/lib.rs, traits/src/registry.rs
Replace Current "ShareAccountIdFor" with improved version where it can handle more than 2 assets.
This might be eventually needed for Stableswap with more than 2 assets in pool.
=> feat: introduce new accountidfor + reorganize registry traits

Cargo.toml, collator-rewards/Cargo.toml, collator-rewards/src/mock.rs, faucet/src/mock.rs, transaction-multi-payment/src/lib.rs, transaction-multi-payment/src/mock.rs, transaction-multi-payment/src/tests.rs
Add structs to the multi tx payment pallet that set and delete tx fee currency on account creation and deletion.
`AddTxAssetOnAccount` sets the tx fee currency on account creation if it is not set already.
`RemoveTxAssetOnKilled` removes the tx fee currency if the system account is removed or if the tx currency balance hits zero.
based on https://github.com/apopiak/open-runtime-module-library/pull/1 (backport of https://github.com/open-web3-stack/open-runtime-module-library/pull/754), we will thus need to maintain a fork of ORML until we're up-to-date in terms of the substrate/polkadot versions
=> Add types to set tx fee asset on new account

nft/Cargo.toml, nft/src/benchmarking.rs, nft/src/lib.rs, nft/src/mock.rs, nft/src/tests.rs, nft/src/types.rs
as is not used anyway and it was just constraining usable types for other pallets
=> refactor!: removed currency type from NFT

nft/Cargo.toml, nft/src/lib.rs, nft/src/tests.rs
Changes:
Permissions checks was moved to extrinsics functions.
Reason:
With current implementation we can't use "internal" functions to create/mint/burn/... nfts from our pallets without allowing it in permissions which result in allowing action for everyone.
=> fix: nft permissions

Cargo.lock, liquidity-mining/Cargo.toml, liquidity-mining/src/lib.rs, liquidity-mining/src/tests/claim_rewards.rs, liquidity-mining/src/tests/create_yield_farm.rs, liquidity-mining/src/tests/deposit_lp_shares.rs, liquidity-mining/src/tests/destroy_global_farm.rs, liquidity-mining/src/tests/full_run.rs, liquidity-mining/src/tests/mock.rs, liquidity-mining/src/tests/redeposit_lp_shares.rs, liquidity-mining/src/tests/test_ext.rs, liquidity-mining/src/tests/tests.rs, liquidity-mining/src/tests/withdraw_lp_shares.rs, traits/Cargo.toml, traits/src/lib.rs, traits/src/liquidity_mining.rs
Bug: Equation for `valued_shares` calculation was not correct.
Fix: Fixed by asking the value of LP shares  directly from AMM.
=> fix: lm valued shares calculation

Cargo.lock, nft/Cargo.toml, nft/src/lib.rs
Fixes #99 
The implementation is consistent with other pallets (e.g. [pallet-balances](https://github.com/paritytech/substrate/blob/a1dee7ecd2a157c490d189f0932b32aa12106857/frame/balances/src/lib.rs#L1486)). 
It's a no-op if `from == to`, meaning that the chain state is not modified so no event needs to be emitted.
=> docs(nft): do_transfer

Cargo.lock, liquidity-mining/Cargo.toml, liquidity-mining/proptest-regressions/tests/invariants.txt, liquidity-mining/src/lib.rs, liquidity-mining/src/tests/claim_rewards.rs, liquidity-mining/src/tests/create_global_farm.rs, liquidity-mining/src/tests/create_yield_farm.rs, liquidity-mining/src/tests/deposit_lp_shares.rs, liquidity-mining/src/tests/destroy_global_farm.rs, liquidity-mining/src/tests/destroy_yield_farm.rs, liquidity-mining/src/tests/full_run.rs, liquidity-mining/src/tests/invariants.rs, liquidity-mining/src/tests/mock.rs, liquidity-mining/src/tests/mod.rs, liquidity-mining/src/tests/resume_yield_farm.rs, liquidity-mining/src/tests/stop_yield_farm.rs, liquidity-mining/src/tests/test_ext.rs, liquidity-mining/src/tests/tests.rs, liquidity-mining/src/tests/update_yield_farm.rs, liquidity-mining/src/tests/withdraw_lp_shares.rs, liquidity-mining/src/types.rs
This PR is adding: 
* support for nondustable whitelist.
* integrity test for `MaxFarmEntriesPerDeposit` configuration.
* `AssetRegistry` - to check if `reward_currency` and `incetivized_asset` are registered and to get information about existential deposit of the tokens.
Nondustable whitelist:
Global-farm’s account is added into the whitelist when a new farm is created and is removed from the whitelist when the farm's owner destroys the farm.
This PR also removes yield-farm’s accounts and replaces it with `YieldFarmData.left_to_distribute` and user’s rewards are transferred directly from the `pot`.
Reason to remove yield-farm’s account is:
Whitelist is not supported by `pallet-balances`used for native currency accounting so to prevent necessity to manage ED on yield-farm’s accounts these …
=> feat: non dustable LM

Cargo.lock, asset-registry/Cargo.toml, asset-registry/src/lib.rs, asset-registry/src/mock.rs, asset-registry/src/tests.rs
This is useful for e.g. integration tests where we might want to set e.g. `LRNA` at genesis to have a certain asset id.
=> extend asset registry genesis config to allow specifying ids at genesis

Cargo.lock, liquidity-mining/Cargo.toml, liquidity-mining/src/lib.rs, liquidity-mining/src/tests/redeposit_lp_shares.rs, traits/Cargo.toml, traits/src/liquidity_mining.rs
This PR updates liquidity-mining's `redeposit_lp_shares()` function to return also `amm_pool_id`. This change is necessary for Basilisk's xyk-liqudity-mining pallet to correctly validate `AssetPair` param from user.
=> feat: return amm_pool_id from redeposit_lp_shares

nft/src/lib.rs, nft/src/mock.rs, nft/src/tests.rs, nft/src/types.rs
Remove unused collection types: `Redeemable`, `Auction` and `HydraHeads`. Use `CollectionTestType` with old fields in the tests to keep the tests untouched (and testing all test cases).
=> refactor(nft): remove unused collection types

ema-oracle/src/benchmarking.rs, ema-oracle/src/tests/mock.rs, ema-oracle/src/tests/mod.rs, ema-oracle/src/types.rs, traits/src/oracle.rs
This PR adds a new oracle period with a = 0.2 (which corresponds to a 9 block oracle when calculating with `smoothing_from_period`).
Based on #182
=> chore: add new oracle period

ema-oracle/src/benchmarking.rs, ema-oracle/src/tests/mock.rs, ema-oracle/src/tests/mod.rs
The tests and benchmarks were using hard-coded values and thus failed in the Basilisk benchmarks.
This fixes these issues.
=> fix: EMA Oracle Benchmarking

ema-oracle/src/benchmarking.rs, ema-oracle/src/lib.rs, ema-oracle/src/tests/mock.rs, ema-oracle/src/tests/mod.rs, ema-oracle/src/types.rs, traits/src/lib.rs, traits/src/oracle.rs
When ingesting data via `on_liquidity_changed` the oracle should calculate the price based on the liquidity, not the amounts.
based on #186 and #182
=> fix: oracle price calculation

Cargo.lock, ema-oracle/Cargo.toml, ema-oracle/src/benchmarking.rs, ema-oracle/src/lib.rs, ema-oracle/src/tests/invariants.rs, ema-oracle/src/tests/mock.rs, ema-oracle/src/tests/mod.rs, traits/src/oracle.rs
This PR switches the oracle price calculation `on_trade` to use the liquidity instead of the trade amounts.
=> fix: Use Liquidity for Price Calculation

Cargo.lock, liquidity-mining/Cargo.toml, liquidity-mining/src/lib.rs, liquidity-mining/src/tests/lm_with_oracle.rs, liquidity-mining/src/tests/mock.rs, liquidity-mining/src/tests/mod.rs, liquidity-mining/src/types.rs, traits/Cargo.toml, traits/src/liquidity_mining.rs
This PR is adding ability to plug external source for `price_adjustment` or use `price_adjustment` stored in global-farm.
In this PR we are adding new trait `PriceAdjustment` with default implementation for `()` which provide `price_adjustment` same way as before.
Why:
On HydraDX we want to use oracle price for `price_adjustment` and on Basilisk we are using value stored in global-farm.
This PR is partial fix for: https://github.com/galacticcouncil/HydraDX-node/issues/529
=> feat: liquidity mining with plugable price_adjustment

Cargo.lock, duster/Cargo.toml, duster/src/lib.rs, duster/src/migration.rs
Set default storage version to 1.
=> feat(duster): default storage version

Cargo.lock, liquidity-mining/Cargo.toml, liquidity-mining/src/lib.rs, liquidity-mining/src/tests/lm_with_oracle.rs, liquidity-mining/src/tests/mock.rs
This PR implements fallback for liquidity-mining `price_adjustment` when oracle is not  available.
We are saving last value of `price_adjustment` from oracle in the `GlobalFarm` and if oracle is not available this last saved value should be used instead of error.
=> Feat:LM price_adjustment fallback when oracle is not available

transaction-multi-payment/src/lib.rs, transaction-multi-payment/src/mock.rs, transaction-multi-payment/src/tests.rs
This PR ensures that a non-zero fee is charged even if the calculated fee in the native currency is small and the non-native fee currency is expensive (low price value).
=> fix: multicurrency payment fee rouding

.devcontainer/Dockerfile, .devcontainer/build-deps.sh, .devcontainer/devcontainer.json, .devcontainer/setup-cargo.sh, .devcontainer/setup.sh, README.md
Adds a Rust devcontainer for use with Github Codespaces.
After merging this you should be able to just drop into a codespace of the repo by clicking on the green "Code" button on the repo main page, choosing "Codespaces" and then picking a branch.
Main usecases I see:
- working on a quick fix that is more complex than a typo (and so needs a dev environment)
- working on the repo if you don't have access to your dev env
- working on sth in parallel while waiting for compilation on your main machine :sweat_smile: 
+ It's surprisingly complex to prebuild dependencies, so compile time is not the best when first starting a codespace.
+ The commits are not verified.
=> add .devcontainer to provide a Rust env for github codespaces
